"""
api.py
------
FastAPI backend for IntelliVault.
 
IMPROVEMENTS OVER ORIGINAL:
  1. Async file I/O (aiofiles) — no longer blocks the event loop on upload
  2. CORS locked to specific origins from config (not wildcard *)
  3. Optional API-key auth via X-API-Key header (set API_KEY in .env)
  4. VectorStore loaded ONCE at startup via lifespan, not per-request
  5. /status no longer loads all chunks into RAM — just checks counts
  6. /upload validates file size (max 20 MB) before writing to disk
  7. All settings imported from config.py — nothing hardcoded
  8. /docs endpoint auto-generated by FastAPI (visit /docs in browser)
"""
 
import os
import json
import logging
from contextlib import asynccontextmanager
 
import aiofiles
from fastapi import FastAPI, UploadFile, File, HTTPException, Depends, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.security.api_key import APIKeyHeader
from pydantic import BaseModel
 
from backend.config import settings
from backend.ingestion.loader import load_document
from backend.ingestion.chunker import chunk_text
from backend.ingestion.embedder import create_embeddings
from backend.ingestion.save_chunks import save_chunks, count_chunks
from backend.retrieval.vector_store import get_vector_store
from backend.rag_pipeline import rag_pipeline
 
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)
 
ALLOWED_EXTS  = {".pdf", ".txt"}
MAX_FILE_SIZE = 20 * 1024 * 1024  # 20 MB
 
# -------------------------------------------------------
# API key auth (optional — only active if API_KEY is set in .env)
# -------------------------------------------------------
_api_key_header = APIKeyHeader(name="X-API-Key", auto_error=False)
 
async def verify_api_key():
    return True
# -------------------------------------------------------
# Lifespan: load heavy resources ONCE at startup
# -------------------------------------------------------
@asynccontextmanager
async def lifespan(app: FastAPI):
    logger.info("[Startup] Loading VectorStore and embedding model...")
    get_vector_store()   # warm up singleton
    from backend.ingestion.embedder import get_model
    get_model()          # warm up embedding model
    logger.info("[Startup] Ready.")
    yield
    logger.info("[Shutdown] Cleaning up.")
 
 
# -------------------------------------------------------
# App
# -------------------------------------------------------
app = FastAPI(
    title="IntelliVault API",
    description="RAG-based document question answering system",
    version="2.0.0",
    lifespan=lifespan,
)
 
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.ALLOWED_ORIGINS.split(","),
    allow_methods=["GET", "POST", "DELETE"],
    allow_headers=["*"],
)
 
 
# -------------------------------------------------------
# Schemas
# -------------------------------------------------------
class QueryRequest(BaseModel):
    query: str
 
 
# -------------------------------------------------------
# POST /upload
# -------------------------------------------------------
@app.post("/upload", dependencies=[Depends(verify_api_key)])
async def upload_file(file: UploadFile = File(...)):
    """
    Upload and index a document (.pdf or .txt, max 20 MB).
 
    Steps:
      1. Validate extension and file size
      2. Write to disk asynchronously (non-blocking)
      3. Extract text → chunk → embed → add to FAISS
      4. Persist chunks + FAISS index
    """
    ext = os.path.splitext(file.filename)[1].lower()
    if ext not in ALLOWED_EXTS:
        raise HTTPException(
            status_code=400,
            detail=f"Unsupported file type '{ext}'. Only .pdf and .txt are allowed."
        )
 
    # Read content once and check size before writing to disk
    content = await file.read()
    if len(content) > MAX_FILE_SIZE:
        raise HTTPException(
            status_code=413,
            detail=f"File too large ({len(content) // 1024} KB). Max allowed: 20 MB."
        )
 
    try:
        file_path = os.path.join(settings.UPLOAD_FOLDER, file.filename)
 
        # Async write — does NOT block the event loop
        async with aiofiles.open(file_path, "wb") as f:
            await f.write(content)
        logger.info(f"[Upload] Saved: {file_path}")
 
        text = load_document(file_path)
        if not text.strip():
            raise HTTPException(status_code=400, detail="File is empty or unreadable.")
 
        chunks = chunk_text(text, source=file.filename)
        if not chunks:
            raise HTTPException(status_code=400, detail="No usable content found in file.")
        logger.info(f"[Upload] {len(chunks)} chunks created.")
 
        embeddings = create_embeddings(chunks)
 
        # Use the singleton store — no repeated disk loads
        store = get_vector_store()
        store.add(embeddings)
        store.save()
 
        total_chunks = save_chunks(chunks)
 
        return {
            "message":       f"'{file.filename}' uploaded and indexed.",
            "chunks_added":  len(chunks),
            "total_chunks":  total_chunks,
            "total_vectors": store.total_vectors,
        }
 
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"[Upload] Failed: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Upload failed: {str(e)}")
 
 
# -------------------------------------------------------
# POST /query
# -------------------------------------------------------
@app.post("/query", dependencies=[Depends(verify_api_key)])
async def query_api(request: QueryRequest):
    """
    Ask a question. Returns answer, sources, and confidence.
 
    Response:
        {
            "answer":       "...",
            "sources":      ["chunk preview...", ...],
            "source_files": ["notes.pdf", ...],
            "confidence":   "high" | "medium" | "low" | "none"
        }
    """
    if not request.query.strip():
        raise HTTPException(status_code=400, detail="Query cannot be empty.")
    try:
        result = rag_pipeline(request.query)
        return result
    except Exception as e:
        logger.error(f"[Query] Failed: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Query failed: {str(e)}")
 
 
# -------------------------------------------------------
# GET /status
# -------------------------------------------------------
@app.get("/status")
def status():
    """
    Returns system health — vector count and chunk count.
    Does NOT load all chunks into RAM (fast).
    """
    store        = get_vector_store()
    total_chunks = count_chunks()  # just reads metadata, not full data
 
    return {
        "status":        "ok",
        "total_vectors": store.total_vectors,
        "total_chunks":  total_chunks,
        "index_synced":  store.total_vectors == total_chunks,
    }
 
 
# -------------------------------------------------------
# DELETE /reset
# -------------------------------------------------------
@app.delete("/reset", dependencies=[Depends(verify_api_key)])
def reset():
    """
    Clear all indexed data (FAISS index + chunks file).
    Resets the in-memory singleton too.
    Does NOT delete uploaded source files.
    """
    from backend.retrieval.vector_store import reset_vector_store
    deleted = []
 
    for path in [settings.INDEX_PATH, settings.CHUNKS_PATH]:
        if os.path.exists(path):
            os.remove(path)
            deleted.append(path)
            logger.info(f"[Reset] Deleted {path}")
 
    reset_vector_store()  # clear singleton so next request starts fresh
 
    return {"message": "Index and chunks cleared.", "deleted": deleted}
# Add this endpoint to your backend/api.py temporarily
# Visit http://127.0.0.1:8000/debug to see what's happening

@app.get("/debug")
def debug_config():
    """
    Shows the active config so you can see exactly why Groq isn't being called.
    Remove this endpoint before going to production.
    """
    from backend.config import settings
    groq_key = settings.GROQ_API_KEY
    return {
        "llm_provider":      settings.LLM_PROVIDER,
        "groq_key_set":      bool(groq_key and groq_key.strip()),
        "groq_key_prefix":   groq_key[:8] + "..." if groq_key else "EMPTY",
        "openai_key_set":    bool(settings.OPENAI_API_KEY),
        "chunks_path":       settings.CHUNKS_PATH,
        "index_path":        settings.INDEX_PATH,
        "top_k":             settings.TOP_K,
        "min_semantic":      settings.MIN_SEMANTIC_SCORE,
        "min_final":         settings.MIN_FINAL_SCORE,
    }